### ISSUE TITLE
Error in lib/gridfs.js when using in production env

### ISSUE THREAD

**Issue by piggyback-nz** [devconcept/multer-gridfs-storage#120]
Hello,

I am using multer-gridfs-storage v4.03. It works fine in my AWS Cloud9 dev environment however I am getting an issue requiring the package in my production environment on an AWS lightsail environment using NGINX reverse proxy and pm2.

The error I am getting is in the gridfs.js file

```
        async    _resolveConnection() {
1|API    |       ^^^^^^^^^^^^^^^^^^
1|API    | SyntaxError: Unexpected identifier
1|API    |     at createScript (vm.js:56:10)
1|API    |     at Object.runInThisContext (vm.js:97:10)
1|API    |     at Module._compile (module.js:549:28)
1|API    |     at Object.Module._extensions..js (module.js:586:10)
1|API    |     at Module.load (module.js:494:32)
1|API    |     at tryModuleLoad (module.js:453:12)
1|API    |     at Function.Module._load (module.js:445:3)
1|API    |     at Function._load (/usr/lib/node_modules/pm2/node_modules/@pm2/io/build/mai
n/metrics/httpMetrics.js:172:43)

```

**Environment**

 -I'm using `multer-gridfs-storage` version 4.03"

- I am connecting to a MongoDB Atlas connection version 4.2.6

- I have Multer 1.4.2 installed to upload files

- The Node version used to run the code is 14

- I'm using Mongoose connection objects to create storage instances. The Mongoose version installed is 5.7.7

Any help would be appreciated. Thanks

**Comment by devconcept** [comment]
I just tested the `develop` branch with node 14 and it works fine. I had this error before while running an old version of Node. Maybe your production branch has an old version of node and you haven't realized. Please verify this for me first.

**Comment by piggyback-nz** [comment]
Hey devconcept, yes I've just resolved this issue. My production branch was actually on node version 6.17 and had to be restarted to be running v14. Thanks for your help, I will close the issue!
