### ISSUE TITLE
Compatability with MongoDB 4+ 

### ISSUE THREAD

**Issue by stevegroom** [devconcept/multer-gridfs-storage#146]
**Describe your problem**

README.md states:  ```Compatibility with MongoDb versions 2 and 3.```

Please clarify - is it compatible with MongoDb v4+ ? 
Is there a better way to do things with MongoDb v4+? 

**Environment**

Current version

**Additional context**

**Comment by devconcept** [comment]
Compatibility in this case refers to the [Node driver](https://mongodb.github.io/node-mongodb-native/) which has a different version than the mongodb database itself. You can use [this table](https://docs.mongodb.com/drivers/node#compatibility) to check if your current driver version is compatible with the database. In your case you need at least version 3.1 of the driver installed.

I'll add this to the readme on the next release.
