### ISSUE TITLE
How do i add new property other the multer default properties

### ISSUE THREAD

**Issue by sadeeqaji** [devconcept/multer-gridfs-storage#17]
### Issue checklist
I'm creating a video on demand Api I want to add Movie Title, Description and category property to my file property  

#### I'm submitting a...

- [ ] Bug report
- [x] Feature request
- [x] Documentation issue or request
- [ ] Support request
- [ ] Regression

#### Environment

- I'm using `multer-gridfs-storage` version *(major.minor.patch)*

- My installed MongoDb version is *(major.minor.patch)*

- I have Multer *(major.minor.patch)* installed to upload files

- I'm *(using/not using)* Mongoose connection objects to create storage instances. The Mongoose version installed is *(major.minor.patch)*

- The Node version used to run the code is *(major.minor.patch)*

**Comment by devconcept** [comment]
Hi, you should try StackOverflow to answer those kinds of questions. Github issues are for when modules have problems or bugs that needs solving.

You should also consider editing the issue and fill in the relevant information. Your issue has no version information included and not a single line of code showing any problem at all. Please edit your message and write your request in a manner that makes sense.

**Comment by sadeeqaji** [comment]
After i uploaded a file to the db  these are property of the file 
`{_id: "5bfd060c3aa43a11c5fb4602",
length: 13633260,
chunkSize: 261120,
uploadDate: "2018-11-27T08:53:33.071Z",
filename: "file.mp4",
md5: "08718641c785a5d2a3c8854665b2b8a8",
contentType: "video/mp4",
metadata: {
TitleOftheMovie: "If you feel ",
Description: "Motivational speech of Jay shetty explaining",
Category: "Motivational"
}
` 
I wanted to add some new property like Title, Description and Category

**Comment by devconcept** [comment]
Please edit your original message and fill all `(major.minor.patch)` with the appropriate versions you are using for each item and write the code your are using otherwise I will close this issue due to lack of information.

**Comment by devconcept** [comment]
I'm closing this issue due to lack of information
