### ISSUE TITLE
can't reference fs.files Schema hasn't been registered for model "fs.files". Use mongoose.model(name, schema)

### ISSUE THREAD

**Issue by sadeeqaji** [devconcept/multer-gridfs-storage#18]
#### I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Support request
- [ ] Regression

#### Environment

- I'm using `multer-gridfs-storage` version *(major.minor.patch)*

- My installed MongoDb version is *(major.minor.patch)*

- I have Multer *(major.minor.patch)* installed to upload files

- I'm *(using/not using)* Mongoose connection objects to create storage instances. The Mongoose version installed is *(major.minor.patch)*

- The Node version used to run the code is *(major.minor.patch)*
v8.11.3
#### Current behavior

Am uploading file to the my mongodb using multergridfs storage i created a movieSchema with fileID property which i reference with id of the file i'm uploading, the fileID is reference is successfully with file id the problem is when try populate method am not getting file property.

#### Expected behavior

Populate the Movie schema with file properties 

Movie schema
`const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const MovieSchema = new Schema({
    description: String,
    category: String,
    token: {
        type: String,
        unique: true,
        expires: '30s'
    },
    fileID: [{
        type: mongoose.Schema.Types.ObjectId,
        ref: 'fs.files'
    }],
    posterID: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'fs.files'
    }
});

const Movie = mongoose.model('Movies', MovieSchema);

module.exports = Movie;`

file upload 
`router.post('/', upload.array('file', 'file'), (req, res) => {
    console.log(req.files)
    const movie = new Movie({
        description: req.body.Description,
        category: req.body.Category,
        token: token,
        fileID: [{
            type: req.files[0].id,
            ref: 'fs.files'
        }],
        posterID: [{
            type: req.files[1].id,
            ref: 'fs.files'
        }]
    });
    console.log(movie)
    movie.save(function(err) {
        if (err) {
            console.log(err);
            return;
        }

        res.json({
            "success": "true"
        });
    });

});

router.get('/movies', (req, res) => {
    Movie
        .find({
            fileID: '5c0ac602105b096fa1688577'
        })
        .populate('fileID', 'fieldname').then(files => {
            res.send(files)
        })
        .catch(err => {
            res.send(err)
        })
})

module.exports = router;`

**Comment by devconcept** [comment]
I'm closing this issue because is related to mongoose and not to this module.

You should try [StackOverflow](https://stackoverflow.com/) to solve that kind of problems. Also when writing issues in github make sure to use the preview tab and format your code appropriately so your request makes sense.

**Comment by sadeeqaji** [comment]
How do i access the fs schema

**Comment by devconcept** [comment]
The `fs` is a special mongodb collection used to store files. You shouldn't try to access it directly unless you know what you are doing. Instead use [`GridFSBucket`](https://mongodb.github.io/node-mongodb-native/3.1/api/GridFSBucket.html) to access your files.

**Comment by sadeeqaji** [comment]
i tried referencing my movieSchema like
        `fileID: {
            type: req.files[0].id,
            ref: 'fs.files'
        },`

because the i have two collection fs.files and fs.chunks so i tried referencing using fs.files

**Comment by devconcept** [comment]
Yes and it is wrong like it is already answered in this [StackOverflow](https://stackoverflow.com/questions/53558684/multer-gridfs-storage-referencing-uploaded-file-to-a-new-collection/53560360#53560360) answer. If you don't read the docs and don't follow the advice your code will never work.

**Comment by sadeeqaji** [comment]
I read the documentation i got stuck fileID is working when tried populate i got this error can't reference fs.files Schema hasn't been registered for model "fs.files". Use mongoose.model(name, schema). the fileID from my Movie Schema is the same with file from fs.file collection, is just that i can't populate the file property to the Movie collection
