### ISSUE TITLE
How do i store a thumbnail for file (video) using

### ISSUE THREAD

**Issue by sadeeqaji** [devconcept/multer-gridfs-storage#19]
#### I'm submitting a...

- [ ] Bug report
- [x] Feature request
- [x] Documentation issue or request
- [x] Support request
- [ ] Regression

#### Environment

- I'm using `multer-gridfs-storage` version *(major.minor.patch)*

- My installed MongoDb version is *(major.minor.patch)*

- I have Multer *(major.minor.patch)* installed to upload files

- I'm *(using/not using)* Mongoose connection objects to create storage instances. The Mongoose version installed is *(major.minor.patch)*

- The Node version used to run the code is *(major.minor.patch)*

#### Expected behavior

Am using array method to upload multiple file one being the video while the other being the thumbnail of the video. How can i store the thumbnail to that particular file?. I was thinking of putting the thumbnail in meta data is it possible ? or is there any way to upload the file and the thumbnail as single array ?

**Comment by devconcept** [comment]
This issue does not have the minimum quality demanded by the issue template regarding new issues therefore will be closed automatically. If you want your issue to be addressed please edit the issue description and fill the information asked by the template.

Errors found:
- No version information provided
- No code sample to reproduce
- Checked more than one type of request
