### ISSUE TITLE
multer-gridfs-storage + Typescript

### ISSUE THREAD

**Issue by ericzon** [devconcept/multer-gridfs-storage#2]
Good job devs, but it would be greater if somebody could add @types/multer-gridfs-storage to work with Typescript.

**Comment by devconcept** [comment]
Typescript support will be added in version 1.1.1

**Comment by devconcept** [comment]
Added typings in PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16304
You can download them using `npm install @types/multer-gridfs-storage`
