### ISSUE TITLE
Upload two file as single Array

### ISSUE THREAD

**Issue by sadeeqaji** [devconcept/multer-gridfs-storage#20]
### Issue checklist

 I'm using this library to backend for my video on demand Api (for handling file upload). File upload is successful, the problem i'm facing is  i want upload to two files as a single Array one being the Video file and the other the thumbnail or Poster of the movie, i tried using `upload.array` but is not uploading as single array that contains the two file. 

#### I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [x ] Documentation issue or request
- [ x] Support request
- [ ] Regression

#### Environment

- I'm using `multer-gridfs-storage` version *(major.minor.patch)*

- My installed MongoDb version is *(major.minor.patch)*

- I have Multer *(major.minor.patch)* installed to upload files

- I'm *(using/not using)* Mongoose connection objects to create storage instances. The Mongoose version installed is *(major.minor.patch)*

- The Node version used to run the code is *(major.minor.patch)*
v8.11.3
#### Current behavior

 I'm using this library to backend for my video on demand Api (for handling file upload). File upload is successful, the problem i'm facing is  i want upload to two files as a single Array one being the Video file and the other the thumbnail or Poster of the movie, i tried using `upload.array` but is not uploading as single array that contains the two file. The code for files upload 
![screenshot from 2018-12-26 13-33-40](https://user-images.githubusercontent.com/16036023/50446120-89a79280-0913-11e9-8d9a-0c94495537ed.png)

How the are File in the Db 
![screenshot from 2018-12-26 13-41-45](https://user-images.githubusercontent.com/16036023/50446228-47cb1c00-0914-11e9-8bc3-361f4cc1afca.png)

#### Expected behavior

Upload video file with its poster or thumbnail as single array like

 `[{Movie}, {Poster/Thumbnail here}]`

**Comment by devconcept** [comment]
I'm closing this issue due to lack of information
