### ISSUE TITLE
webkitRelativePath is lost in file handler

### ISSUE THREAD

**Issue by yangyaochia** [devconcept/multer-gridfs-storage#357]
**Describe the bug**

In the file handler, I can't see the file.webkitRelativePath passed by the frontend client.
I would like to preserve the relative path when uploading a folder.

Also, file.originalName is only left with the filename, the relativepath is gone.

                let fileHandler = (req: any, file: any) => { 
                    debuglog( () => { return JSON.stringify(file)})
                    return { bucketName: type, metadata: { id: req.body.id as string, username: req.user.username as string}, filename: file.webkitRelativePath? file.webkitRelativePath: file.originalName }
                }
                storage = new GridFsStorage({
                    db: db,
                    cache: true,
                    file: fileHandler
                });

**Environment**

- I'm using `multer-gridfs-storage` version *(5.0.0)*

- My installed MongoDb version is *(4.4.2)*

- I have Multer *(1.4.2)* installed to upload files

- The Node version used to run the code is *(1.4.2)*

- I'm not using Mongoose connection objects to create storage instances. 

**To Reproduce**

1. upload folder with formdata. (I can confirm that each file contains webkitRelativePath)
2. on nodejs file hanlder, only see the filename instead of the relative path

**Expected behavior**

**Comment by devconcept** [comment]
What you receive in this function comes directly from [multer](https://github.com/expressjs/multer#file-information). This module doesn't collect any information from the request since this is the multer library role. This is not a bug but the expected behavior.

You should open a ticket in their repository and when they publish a fix your issue will be solved automatically.

**Comment by yangyaochia** [comment]
I can see this file.webkitRelativePath when using multer standalone though.....

**Comment by yangyaochia** [comment]
I can confirm that this is from multer.
I need to set preservePath to true as the option.

Thanks for confirming
