### ISSUE TITLE
[Mongoose] Listening to events on the Db class has been deprecated and will be removed in the next major version

### ISSUE THREAD

**Issue by midrissi** [devconcept/multer-gridfs-storage#382]
**Describe the bug**

Using the mongoose `connection` as a `db` throws this warning:

```
Listening to events on the Db class has been deprecated and will be removed in the next major version.
```

My code looks like this:

```javascript
const { connection } = require('mongoose');
const { GridFsStorage } = require('multer-gridfs-storage');

const storage = new GridFsStorage({
  db: connection,
});
```

**Environment**

- I'm using `multer-gridfs-storage` version *5.0.1*

- I have Multer *1.4.3* installed to upload files

- The Node version used to run the code is *16.3.0*

- I'm *using* Mongoose connection objects to create storage instances. The Mongoose version installed is *5.12.13*

After upgrading to the latest version of `mongoose`, [this line](https://github.com/devconcept/multer-gridfs-storage/blob/master/src/gridfs.ts#L502) throws an exception.

**Comment by devconcept** [comment]
Could you please answer the following:

Are you using mongodb as part of mongoose or you have it as a separate dependency in your package.json as well?

If you have both can you verify that the version in both cases is the same?

As specified [here](https://github.com/devconcept/multer-gridfs-storage/blob/4839e481715891fe0b2631abd373300bf1c93669/src/utils.ts#L22) the module only listens on the db object in some specific cases only. Any mongodb version greater than 4 will use the client as the event source

**Comment by devconcept** [comment]
This issue will be closed automatically for inactivity in 4 days

**Comment by devconcept** [comment]
This issue is closed due to inactivity
