### ISSUE TITLE
DeprecationWarning from MongoClient

### ISSUE THREAD

**Issue by bailor1** [devconcept/multer-gridfs-storage#503]
**Describe the bug**
When used with MongoDB v5, the following deprecation warning is displayed due to the usage of `isConnected()` within multer-gridfs-storage:
```
(node:19016) DeprecationWarning: isConnected is deprecated and will be removed in the next major version
```

**Environment**
- I'm using `multer-gridfs-storage` version 5.0.2

- My installed MongoDb version is 5.0.8

- I have Multer 1.4.3 installed to upload files

- The Node version used to run the code is 17.4.0

**To Reproduce**
Simply create a new GridFsStorage in node.
I traced the depreciation from the `new GridFsStorage()` call (not including parameters because they're irrelevant to the deprecation):
```
    at GridFsStorage._updateConnectionStatus (myapp/node_modules/multer-gridfs-storage/lib/gridfs.js:407:33)
    at GridFsStorage._setDb (myapp/node_modules/multer-gridfs-storage/lib/gridfs.js:446:14)
    at GridFsStorage._connect (myapp/node_modules/multer-gridfs-storage/lib/gridfs.js:335:18)
    at new GridFsStorage (myapp/node_modules/multer-gridfs-storage/lib/gridfs.js:91:14)
    at singleFileUpload (myapp/api/src/routes/file.js:46:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
The warning occurs because of the `isConnected()` call in the following screenshot:
![Screenshot from 2022-08-10 14-57-33](https://user-images.githubusercontent.com/78231932/183995376-52e5c210-59e8-4ccb-9ceb-b6c676b08bc8.png)

The warning is thrown within `myapp/node_modules/mongodb/lib/mongo_client.js`:
![Screenshot from 2022-08-10 14-59-34](https://user-images.githubusercontent.com/78231932/183995679-494919b8-cb62-4756-aa85-91380e474ed3.png)

**Expected behavior**
Not showing the warning/the package no longer being deprecated

**Comment by bailor1** [comment]
Perhaps this Mongo documentation about moving away from `isConnecte()d` could be of use: https://mongodb.github.io/node-mongodb-native/3.3/reference/unified-topology/

**Comment by devconcept** [comment]
If you check the code you'll see that the `isConnected` function is only executed if is present. When the function is finally removed it will not be used anymore and the library . The warning is the price to pay for compatibility.
