### ISSUE TITLE
do you use file system underneath for stream files?

### ISSUE THREAD

**Issue by alirezaRaisSattari** [devconcept/multer-gridfs-storage#514]
do you use file system underneath for stream files?
in stackoverflow everyone use file system for create stream file like:
fs.createReadStream(uploadFilePath)
do you use this too?

**Comment by devconcept** [comment]
No. These files are streamed directly to mongodb. If you want to stream twice you can use the default file storage and then use the standard mongodb streams or this module to pipe to the database depending on your needs. If you want a different order then use this module to store in the database and then use the standard mongodb streams to move from there to the filesystem
