### ISSUE TITLE
Issue with Mongoose 5.0

### ISSUE THREAD

**Issue by deresegetachew** [devconcept/multer-gridfs-storage#8]
You might run into issues when connecting using mongoose 5.0 while following the examples provided here and on gridfs_stream. So Consider using mongoose V4.. for gridfs and mongoose 5.0 for your mongoDB .on how to install same packages of different version follow this https://gist.github.com/mnpenner/c46a5eff34cfa91f361a8b3baa249a10

**Comment by devconcept** [comment]
This library has no dependencies with mongoose or gridfs-stream. Please check the [`package.json`](https://github.com/devconcept/multer-gridfs-storage/blob/master/package.json) file before opening issues.

**Comment by devconcept** [comment]
Check #9. It might be what you need. Without more information is impossible to know what is the nature of your problem.
